#!/usr/bin/env node
'use strict';

var LamassuConfig = require('lamassu-config');
var promptly = require('promptly');

var config = new LamassuConfig();

updateDb(function(err) {
  if (err) throw err;
  console.log('\nSuccess.');
});

function updateDb(callback) {
  var newConfig = {
    exchanges: {
      plugins: {
        settings: {
          mrcoin: {
            ticker_url: 'https://www.mrcoin.eu/api/v1/atm_price_ticker'
          }
        },
        current: {
          ticker: 'mrcoin'
        }
      }
    }
  };
  config.mergeConfig(newConfig, callback);
}
